// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cases.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCase = `-- name: CreateCase :one
INSERT INTO cases (
    id, 
    title, 
    description, 
    created_at, 
    updated_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, created_at, updated_at
`

type CreateCaseParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateCase(ctx context.Context, arg CreateCaseParams) (Case, error) {
	row := q.db.QueryRowContext(ctx, createCase,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCaseByID = `-- name: GetCaseByID :one
SELECT id, title, description, created_at, updated_at 
FROM cases
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetCaseByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRowContext(ctx, getCaseByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCases = `-- name: ListCases :many
SELECT id, title, description, created_at, updated_at 
FROM cases
ORDER BY created_at DESC
`

func (q *Queries) ListCases(ctx context.Context) ([]Case, error) {
	rows, err := q.db.QueryContext(ctx, listCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Case
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
