// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (
    id,
    case_id,
    title,
    description,
    event_date,
    date_precision,
    created_at,
    updated_at
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, case_id, title, event_date, created_at, updated_at, description, date_precision
`

type CreateMilestoneParams struct {
	ID            uuid.UUID `json:"id"`
	CaseID        uuid.UUID `json:"case_id"`
	Title         string    `json:"title"`
	Description   *string   `json:"description"`
	EventDate     time.Time `json:"event_date"`
	DatePrecision string    `json:"date_precision"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, createMilestone,
		arg.ID,
		arg.CaseID,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.DatePrecision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Title,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.DatePrecision,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones
WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMilestone, id)
	return err
}

const getMilestoneByID = `-- name: GetMilestoneByID :one
SELECT id, title, description, created_at, updated_at 
FROM cases
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetMilestoneByID(ctx context.Context, id uuid.UUID) (Case, error) {
	row := q.db.QueryRowContext(ctx, getMilestoneByID, id)
	var i Case
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMilestonesByCase = `-- name: ListMilestonesByCase :many
SELECT id, case_id, title, event_date, created_at, updated_at, description, date_precision 
FROM milestones
WHERE case_id = $1
ORDER BY event_date ASC
`

func (q *Queries) ListMilestonesByCase(ctx context.Context, caseID uuid.UUID) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestonesByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Title,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.DatePrecision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
