// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, hashed_password, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, hashed_password, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, created_at, updated_at 
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, created_at, updated_at 
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchHistoryByUserID = `-- name: GetWatchHistoryByUserID :many
SELECT 
    wh.id AS watch_id,
    wh.watched_at,
    wh.completed,
    v.id AS video_id,
    v.youtube_video_id,
    v.title,
    v.channel_name
FROM watch_history wh
JOIN videos v ON wh.video_id = v.id
WHERE wh.user_id = $1
ORDER BY wh.watched_at DESC
`

type GetWatchHistoryByUserIDRow struct {
	WatchID        uuid.UUID `json:"watch_id"`
	WatchedAt      time.Time `json:"watched_at"`
	Completed      bool      `json:"completed"`
	VideoID        uuid.UUID `json:"video_id"`
	YoutubeVideoID string    `json:"youtube_video_id"`
	Title          string    `json:"title"`
	ChannelName    string    `json:"channel_name"`
}

func (q *Queries) GetWatchHistoryByUserID(ctx context.Context, userID uuid.UUID) ([]GetWatchHistoryByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getWatchHistoryByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWatchHistoryByUserIDRow
	for rows.Next() {
		var i GetWatchHistoryByUserIDRow
		if err := rows.Scan(
			&i.WatchID,
			&i.WatchedAt,
			&i.Completed,
			&i.VideoID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordVideoWatch = `-- name: RecordVideoWatch :one
INSERT INTO watch_history (id, user_id, video_id, watched_at, completed)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, video_id) 
DO UPDATE SET 
    watched_at = EXCLUDED.watched_at,
    completed = EXCLUDED.completed
RETURNING id, user_id, video_id, watched_at, completed
`

type RecordVideoWatchParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	VideoID   uuid.UUID `json:"video_id"`
	WatchedAt time.Time `json:"watched_at"`
	Completed bool      `json:"completed"`
}

func (q *Queries) RecordVideoWatch(ctx context.Context, arg RecordVideoWatchParams) (WatchHistory, error) {
	row := q.db.QueryRowContext(ctx, recordVideoWatch,
		arg.ID,
		arg.UserID,
		arg.VideoID,
		arg.WatchedAt,
		arg.Completed,
	)
	var i WatchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoID,
		&i.WatchedAt,
		&i.Completed,
	)
	return i, err
}
