// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    id,
    milestone_id,
    youtube_video_id,
    title,
    channel_name,
    published_at,
    created_at,
    updated_at,
    category
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, milestone_id, youtube_video_id, title, channel_name, published_at, created_at, updated_at, category
`

type CreateVideoParams struct {
	ID             uuid.UUID     `json:"id"`
	MilestoneID    uuid.NullUUID `json:"milestone_id"`
	YoutubeVideoID string        `json:"youtube_video_id"`
	Title          string        `json:"title"`
	ChannelName    string        `json:"channel_name"`
	PublishedAt    time.Time     `json:"published_at"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Category       string        `json:"category"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.MilestoneID,
		arg.YoutubeVideoID,
		arg.Title,
		arg.ChannelName,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Category,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.YoutubeVideoID,
		&i.Title,
		&i.ChannelName,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
	)
	return i, err
}

const listUnlinkedVideos = `-- name: ListUnlinkedVideos :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, published_at, created_at, updated_at, category 
FROM videos
WHERE milestone_id IS NULL
ORDER BY published_at DESC
`

func (q *Queries) ListUnlinkedVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listUnlinkedVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByMilestone = `-- name: ListVideosByMilestone :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, published_at, created_at, updated_at, category 
FROM videos
WHERE milestone_id = $1
ORDER BY published_at ASC
`

func (q *Queries) ListVideosByMilestone(ctx context.Context, milestoneID uuid.NullUUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByMilestone, milestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
