// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    id,
    milestone_id,
    youtube_video_id,
    title,
    channel_name,
    description,
    published_at,
    created_at,
    updated_at,
    category,
    status,
    raw_transcript
) 
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source
`

type CreateVideoParams struct {
	ID             uuid.UUID     `json:"id"`
	MilestoneID    uuid.NullUUID `json:"milestone_id"`
	YoutubeVideoID string        `json:"youtube_video_id"`
	Title          string        `json:"title"`
	ChannelName    string        `json:"channel_name"`
	Description    string        `json:"description"`
	PublishedAt    time.Time     `json:"published_at"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Category       string        `json:"category"`
	Status         string        `json:"status"`
	RawTranscript  *string       `json:"raw_transcript"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.MilestoneID,
		arg.YoutubeVideoID,
		arg.Title,
		arg.ChannelName,
		arg.Description,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Category,
		arg.Status,
		arg.RawTranscript,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.YoutubeVideoID,
		&i.Title,
		&i.ChannelName,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Status,
		&i.AiSummary,
		&i.RawTranscript,
		&i.EstimatedEventDate,
		&i.TranscriptProcessedAt,
		&i.SummarySource,
	)
	return i, err
}

const getPendingTranscripts = `-- name: GetPendingTranscripts :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source 
FROM videos
WHERE raw_transcript IS NOT NULL 
  AND transcript_processed_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingTranscripts(ctx context.Context, limit int32) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTranscripts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Status,
			&i.AiSummary,
			&i.RawTranscript,
			&i.EstimatedEventDate,
			&i.TranscriptProcessedAt,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source
FROM videos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.YoutubeVideoID,
		&i.Title,
		&i.ChannelName,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Status,
		&i.AiSummary,
		&i.RawTranscript,
		&i.EstimatedEventDate,
		&i.TranscriptProcessedAt,
		&i.SummarySource,
	)
	return i, err
}

const linkVideoToMilestone = `-- name: LinkVideoToMilestone :exec
UPDATE videos
SET milestone_id = $1,
    updated_at = $3
WHERE id = $2
`

type LinkVideoToMilestoneParams struct {
	MilestoneID uuid.NullUUID `json:"milestone_id"`
	ID          uuid.UUID     `json:"id"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

func (q *Queries) LinkVideoToMilestone(ctx context.Context, arg LinkVideoToMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, linkVideoToMilestone, arg.MilestoneID, arg.ID, arg.UpdatedAt)
	return err
}

const listPendingVideos = `-- name: ListPendingVideos :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source
FROM videos
WHERE status = 'pending_review'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listPendingVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Status,
			&i.AiSummary,
			&i.RawTranscript,
			&i.EstimatedEventDate,
			&i.TranscriptProcessedAt,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnlinkedVideos = `-- name: ListUnlinkedVideos :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source 
FROM videos
WHERE milestone_id IS NULL
ORDER BY published_at DESC
`

func (q *Queries) ListUnlinkedVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listUnlinkedVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Status,
			&i.AiSummary,
			&i.RawTranscript,
			&i.EstimatedEventDate,
			&i.TranscriptProcessedAt,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByMilestone = `-- name: ListVideosByMilestone :many
SELECT id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source 
FROM videos
WHERE milestone_id = $1 
  AND status = 'approved'
ORDER BY COALESCE(estimated_event_date, published_at) ASC
`

func (q *Queries) ListVideosByMilestone(ctx context.Context, milestoneID uuid.NullUUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByMilestone, milestoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.MilestoneID,
			&i.YoutubeVideoID,
			&i.Title,
			&i.ChannelName,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Status,
			&i.AiSummary,
			&i.RawTranscript,
			&i.EstimatedEventDate,
			&i.TranscriptProcessedAt,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkVideoFromMilestone = `-- name: UnlinkVideoFromMilestone :exec
UPDATE videos
SET milestone_id = NULL,
    updated_at = $2
WHERE id = $1
`

type UnlinkVideoFromMilestoneParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UnlinkVideoFromMilestone(ctx context.Context, arg UnlinkVideoFromMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, unlinkVideoFromMilestone, arg.ID, arg.UpdatedAt)
	return err
}

const updateVideoAnalysis = `-- name: UpdateVideoAnalysis :one
UPDATE videos
SET 
    category = $2,
    ai_summary = $3,
    estimated_event_date = $4,
    summary_source = $5,
    status = $6,
    updated_at = $7
WHERE id = $1
RETURNING id, milestone_id, youtube_video_id, title, channel_name, description, published_at, created_at, updated_at, category, status, ai_summary, raw_transcript, estimated_event_date, transcript_processed_at, summary_source
`

type UpdateVideoAnalysisParams struct {
	ID                 uuid.UUID    `json:"id"`
	Category           string       `json:"category"`
	AiSummary          *string      `json:"ai_summary"`
	EstimatedEventDate sql.NullTime `json:"estimated_event_date"`
	SummarySource      string       `json:"summary_source"`
	Status             string       `json:"status"`
	UpdatedAt          time.Time    `json:"updated_at"`
}

func (q *Queries) UpdateVideoAnalysis(ctx context.Context, arg UpdateVideoAnalysisParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoAnalysis,
		arg.ID,
		arg.Category,
		arg.AiSummary,
		arg.EstimatedEventDate,
		arg.SummarySource,
		arg.Status,
		arg.UpdatedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.MilestoneID,
		&i.YoutubeVideoID,
		&i.Title,
		&i.ChannelName,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Status,
		&i.AiSummary,
		&i.RawTranscript,
		&i.EstimatedEventDate,
		&i.TranscriptProcessedAt,
		&i.SummarySource,
	)
	return i, err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos
SET status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateVideoStatusParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
